CREATE TABLE IF NOT EXISTS catalogo.tipo_operacion (
    codigo          VARCHAR(4) NOT NULL,
    descripcion     VARCHAR(200) NOT NULL,
    es_exportacion  BOOLEAN NOT NULL DEFAULT FALSE,
    es_detraccion   BOOLEAN NOT NULL DEFAULT FALSE,
    es_percepcion   BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_tipo_operacion PRIMARY KEY (codigo)
);

INSERT INTO catalogo.tipo_operacion (codigo, descripcion, es_exportacion, es_detraccion, es_percepcion) VALUES
('0101','VENTA INTERNA', FALSE, FALSE, FALSE),
('0200','EXPORTACION', TRUE, FALSE, FALSE),
('0201','EXPORTACION - BIENES', TRUE, FALSE, FALSE),
('0202','EXPORTACION - SERVICIOS', TRUE, FALSE, FALSE),
('0203','EXPORTACION - MUESTRAS GRATUITAS', TRUE, FALSE, FALSE),
('0300','SERVICIOS PRESTADOS A NO DOMICILIADOS', FALSE, FALSE, FALSE),
('0400','TRANSPORTE INTERNACIONAL DE CARGA', FALSE, FALSE, FALSE),
('0500','TRANSPORTE INTERNACIONAL DE PASAJEROS', FALSE, FALSE, FALSE),
('0600','SERVICIOS PRESTADOS A ZONA DE COMERCIO', FALSE, FALSE, FALSE),
('1001','OPERACION SUJETA A DETRACCION', FALSE, TRUE, FALSE),
('2001','OPERACION SUJETA A PERCEPCION', FALSE, FALSE, TRUE),
('6001','RESTAURANTES Y HOTELES - 10%', FALSE, FALSE, FALSE),
('6002','ESTACIONAMIENTO - 5%', FALSE, FALSE, FALSE),
('1101','ZONA DE COMERCIO', FALSE, FALSE, FALSE)
ON CONFLICT (codigo) DO NOTHING;
