CREATE TABLE IF NOT EXISTS catalogo.unidad_medida (
    codigo          VARCHAR(10) NOT NULL,
    nombre          VARCHAR(100) NOT NULL,

    CONSTRAINT pk_unidad_medida PRIMARY KEY (codigo)
);

INSERT INTO catalogo.unidad_medida (codigo, nombre) VALUES
('UND','UNIDAD'),
('KG','KILOGRAMO'),
('G','GRAMO'),
('L','LITRO'),
('M','METRO'),
('M2','METRO CUADRADO'),
('M3','METRO CUBICO'),
('CM','CENTIMETRO'),
('MM','MILIMETRO'),
('TON','TONELADA'),
('CAJ','CAJA'),
('BOT','BOTELLA'),
('PQT','PAQUETE'),
('SAC','SACO'),
('CIENT','CIENTOS'),
('MILL','MILLAR'),
('JGO','JUEGO'),
('PAR','PAR'),
('DZN','DOCENA'),
('GLL','GALON'),
('HH','HORA HORA'),
('DIA','DIA'),
('MES','MES'),
('OAN','ANIO'),
('SERV','SERVICIO'),
('OTROS','OTROS'),
('ACT','ACTIVIDAD'),
('BOL','BOLSA'),
('FAR','FARDO'),
('TNE','TONELADA METRICA'),
('SM','SEGUNDO'),
('QUI','QUINTAL'),
('BX','BOLSA'),
('DPC','DECENA'),
('CIEN','CIENTO'),
('OCT','OCTAVO'),
('PZA','PIEZA'),
('PAQ','PAQUETE'),
('ENV','ENVASE'),
('BAR','BARRIL')
ON CONFLICT (codigo) DO NOTHING;
